### ISSUE TITLE
数组越界 不知道怎么搞了

### ISSUE THREAD

**Issue by ghost** [K-bai/meumy-live-showcase#2]
(base) [root@VM-20-10-centos server]# python danmu_analyse.py
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.813 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/rec/server/danmu_analyse.py", line 378, in <module>
    dir_update()
  File "/rec/server/danmu_analyse.py", line 275, in dir_update
    if live_list[0][0] != None:
IndexError: list index out of range

**Comment by ghost** [comment]
已经发现问题了
低于5分钟的直播就没处理好
怪不得正常人不会碰到
回头改一下处理部分
